/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_asocial_games_neptun_dungeonmaker_DungeonMaker */

#ifndef _Included_ru_asocial_games_neptun_dungeonmaker_DungeonMaker
#define _Included_ru_asocial_games_neptun_dungeonmaker_DungeonMaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_asocial_games_neptun_dungeonmaker_DungeonMaker
 * Method:    generateDungeon
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_asocial_games_neptun_dungeonmaker_DungeonMaker_generateDungeon
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
